# Generated by Django 5.0.2 on 2024-05-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/defaultEntreprise.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
